import hre from "hardhat";
import { encodeAbiParameters } from "viem";
import fs from "fs";
import path from "path";

/**
 * Deploy script for ERC-8004 upgradeable contracts using UUPS proxy pattern
 *
 * USAGE: npx hardhat run scripts/deploy.ts
 */
async function main() {
  const { viem } = await hre.network.connect();
  const [deployer] = await viem.getWalletClients();

  console.log("Deploying ERC-8004 Upgradeable Contracts");
  console.log("========================================");
  console.log("Deployer address:", deployer.account.address);
  console.log("");

  // --- 1. Identity Registry ---
  console.log("1. Deploying IdentityRegistry...");
  const identityImpl = await viem.deployContract("IdentityRegistryUpgradeable");
  const identityInitData = "0x8129fc1c" as `0x${string}`; // initialize()
  const identityProxy = await viem.deployContract("ERC1967Proxy", [
    identityImpl.address,
    identityInitData
  ]);
  // We don't strictly need to get the contract instance for verification, just addresses
  console.log(`   Impl:  ${identityImpl.address}`);
  console.log(`   Proxy: ${identityProxy.address}`);

  // --- 2. Reputation Registry ---
  console.log("2. Deploying ReputationRegistry...");
  const reputationImpl = await viem.deployContract(
    "ReputationRegistryUpgradeable"
  );
  const reputationInitData = ("0xc4d66de8" +
    encodeAbiParameters(
      [{ name: "identityRegistry", type: "address" }],
      [identityProxy.address]
    ).slice(2)) as `0x${string}`; // initialize(address)
  const reputationProxy = await viem.deployContract("ERC1967Proxy", [
    reputationImpl.address,
    reputationInitData
  ]);
  console.log(`   Impl:  ${reputationImpl.address}`);
  console.log(`   Proxy: ${reputationProxy.address}`);

  // --- 3. Validation Registry ---
  console.log("3. Deploying ValidationRegistry...");
  const validationImpl = await viem.deployContract(
    "ValidationRegistryUpgradeable"
  );
  const validationInitData = ("0xc4d66de8" +
    encodeAbiParameters(
      [{ name: "identityRegistry", type: "address" }],
      [identityProxy.address]
    ).slice(2)) as `0x${string}`; // initialize(address)
  const validationProxy = await viem.deployContract("ERC1967Proxy", [
    validationImpl.address,
    validationInitData
  ]);
  console.log(`   Impl:  ${validationImpl.address}`);
  console.log(`   Proxy: ${validationProxy.address}`);

  console.log("");
  console.log("✅ All contracts deployed successfully!");

  // --- Auto-Generate Manual Verification Helper Script ---
  const verifyScriptContent = `#!/bin/bash
set -e

# Auto-generated verification script (generated by deploy.ts)
# Run this to generate metadata bundles for manual verification.

# 1. Clean previous runs
rm -f verify-bundles/MANIFEST.txt
# We let generate_metadata_bundle.sh create the header.

# 2. Export Implementation Addresses (for MANIFEST.txt)
export IDENTITYREGISTRYUPGRADEABLE_ADDRESS=${identityImpl.address}
export REPUTATIONREGISTRYUPGRADEABLE_ADDRESS=${reputationImpl.address}
export VALIDATIONREGISTRYUPGRADEABLE_ADDRESS=${validationImpl.address}

echo "Generating bundles for Implementations..."
./generate_metadata_bundle.sh IdentityRegistryUpgradeable ReputationRegistryUpgradeable ValidationRegistryUpgradeable

# 3. Export One Proxy Address (to serve as the example in manifest)
export ERC1967PROXY_ADDRESS=${identityProxy.address}

echo "Generating bundle for Proxy..."
./generate_metadata_bundle.sh ERC1967Proxy

# 4. Append Specific Proxy Details to Manifest
MANIFEST="verify-bundles/MANIFEST.txt"

{
  echo "----------------------------------------------------------"
  echo "DETAILED PROXY VERIFICATION DATA"
  echo "----------------------------------------------------------"
  echo ""
  echo "1. ERC1967Proxy (Identity Registry)"
  echo "   Address: ${identityProxy.address}"
  echo "   Verify using file: verify-bundles/ERC1967Proxy/metadata.json"
  echo "   Constructor Arguments (ABI Encoded):"
  echo "     _logic: ${identityImpl.address}"
  echo "     _data:  ${identityInitData}"
  echo ""
  echo "2. ERC1967Proxy (Reputation Registry)"
  echo "   Address: ${reputationProxy.address}"
  echo "   Verify using file: verify-bundles/ERC1967Proxy/metadata.json"
  echo "   Constructor Arguments (ABI Encoded):"
  echo "     _logic: ${reputationImpl.address}"
  echo "     _data:  ${reputationInitData}"
  echo ""
  echo "3. ERC1967Proxy (Validation Registry)"
  echo "   Address: ${validationProxy.address}"
  echo "   Verify using file: verify-bundles/ERC1967Proxy/metadata.json"
  echo "   Constructor Arguments (ABI Encoded):"
  echo "     _logic: ${validationImpl.address}"
  echo "     _data:  ${validationInitData}"
  echo ""
} >> "$MANIFEST"

echo ""
echo "✅ Verification bundles generated in verify-bundles/"
echo "👉 Open verify-bundles/MANIFEST.txt to see instructions."
`;

  const scriptPath = path.join(
    process.cwd(),
    "make_sourcify_inline_metadata.sh"
  );
  fs.writeFileSync(scriptPath, verifyScriptContent);
  try {
    fs.chmodSync(scriptPath, "755");
  } catch (e) {}
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
